server:
  port: 9999
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ThriveX?characterEncoding=utf-8&useSSL=false
    username: root
    password: liuyuyang